using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using InsuranceCompareTool.Domain;
using InsuranceCompareTool.Models;
using InsuranceCompareTool.ShareCommon;
using InsuranceCompareTool.ShareCommon.ValueConverter;
using InsuranceCompareTool.ViewModels;
using Xceed.Wpf.Toolkit;
namespace InsuranceCompareTool.Views
{
    /// <summary>
    /// Interaction logic for AssignView
    /// </summary>
    public partial class AssignView 
    {
        private readonly List<string> mSystemColumns = new List<string>();
        private readonly List<string> mDateColumns = new List<string>();
        private readonly List<string> mIntColumns = new List<string>();
        private readonly List<string> mNumberColumns = new List<string>();

        public AssignView()
        {
            InitializeComponent();

            var logger = new VisualLogger
            {
                TextBox = T_Log
            };
            log4net.Config.BasicConfigurator.Configure(logger);

            foreach(var col in BillTableColumns.Columns.Where(a=>a.IsSystemColumn))
            {
                mSystemColumns.AddRange(col.Name);
            }

            foreach(var col in BillTableColumns.Columns.Where(a=>a.Type == typeof(DateTime)))
            {
                mDateColumns.AddRange(col.Name);
            }

            foreach (var col in BillTableColumns.Columns.Where(a => a.Type == typeof(int)))
            {
                mIntColumns.AddRange(col.Name);
            }

            foreach (var col in BillTableColumns.Columns.Where(a => a.Type == typeof(double)))
            {
                mNumberColumns.AddRange(col.Name);
            }
        }
        private void DataGrid_OnAutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            var col = e.Column as DataGridTextColumn;

            if(col != null)
            {
                if(mSystemColumns.Contains(e.PropertyName))
                {
                    e.Cancel = true;
                }
                Style s = new Style();
                s.Setters.Add(new Setter() { Property = TextBlock.TextWrappingProperty, Value = TextWrapping.Wrap });
                s.Setters.Add(new Setter() { Property = TextBlock.HeightProperty, Value = (double.NaN)});
                if(mIntColumns.Contains(e.PropertyName))
                {
                    s.Setters.Add(new Setter(){ Property = TextBlock.HorizontalAlignmentProperty, Value =  HorizontalAlignment.Center});
                }

                if(mNumberColumns.Contains(e.PropertyName))
                {
                    s.Setters.Add(new Setter() { Property = TextBlock.HorizontalAlignmentProperty, Value = HorizontalAlignment.Right }); 
                }

                col.ElementStyle = s;
                DataGridTextColumn dc = e.Column as DataGridTextColumn;
                System.Windows.Data.Binding binding = dc.Binding as Binding;
                if(mDateColumns.Contains(binding.Path.Path))
                {
                    binding.StringFormat = "d";
                }


                //col.CellStyle.Setters.Add(new  Setter(){ Property = TextBlock.TextWrappingProperty, Value = TextWrapping.Wrap });
                //col.CellStyle.Setters.Add(new  Setter(){ Property = TextBlock.HeightProperty, Value =90}); 
            }
        }
        private void DataGrid_OnAutoGeneratedColumns(object sender, EventArgs e)
        {

            var vm = this.DataContext as AssignViewViewModel;
            var dataGrid = sender as DataGrid;
            for(var i = 0; i < dataGrid.Columns.Count; i++)
            {
                var colData = vm.Columns.FirstOrDefault(a => a.Index == i);
                var colIndex = vm.Columns.IndexOf(colData);

                var col = dataGrid.Columns[i];
                col.DisplayIndex = colIndex;

                Binding b = new Binding();
                b.Source = this.DataContext;
                b.Path = new PropertyPath($"Columns[{colIndex}].IsVisible");
                b.Converter = new Boolean2VisibleConverter();
                BindingOperations.SetBinding(col, DataGridColumn.VisibilityProperty, b);
            }
        }
        private void ButtonBase_OnClick(object sender, RoutedEventArgs e)
        {
            T_Log.Document.Blocks.Clear();
        }
    }
}
