using System;
using System.Collections.Generic;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using InsuranceCompareTool.Models;
using InsuranceCompareTool.ShareCommon.ValueConverter;
namespace InsuranceCompareTool.Views
{
    /// <summary>
    /// Interaction logic for AssignView
    /// </summary>
    public partial class AssignView 
    {
        private readonly List<string> mSystemColumns = new List<string>() {
            BillSheetColumns.SYS_FILTER,
            BillSheetColumns.SYS_FINISHED,
            BillSheetColumns.SYS_HISTORY
        };

        public AssignView()
        {
            InitializeComponent();
        }
        private void DataGrid_OnAutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            var col = e.Column as DataGridTextColumn;

            if(col != null)
            {
                if(mSystemColumns.Contains(e.PropertyName))
                {
                    e.Cancel = true;
                }
                Style s = new Style();
                s.Setters.Add(new Setter() { Property = TextBlock.TextWrappingProperty, Value = TextWrapping.Wrap });
                s.Setters.Add(new Setter() { Property = TextBlock.HeightProperty, Value = (double.NaN)});
                col.ElementStyle = s;
                //col.CellStyle.Setters.Add(new  Setter(){ Property = TextBlock.TextWrappingProperty, Value = TextWrapping.Wrap });
                //col.CellStyle.Setters.Add(new  Setter(){ Property = TextBlock.HeightProperty, Value =90}); 
            }
        }
        private void DataGrid_OnAutoGeneratedColumns(object sender, EventArgs e)
        {
            var dataGrid = sender as DataGrid;
            for(var i = 0; i < dataGrid.Columns.Count; i++)
            {
                var col = dataGrid.Columns[i];
                Binding b = new Binding();
                b.Source = this.DataContext;
                b.Path = new PropertyPath($"Columns[{i}].IsVisible");
                b.Converter = new Boolean2VisibleConverter();
                BindingOperations.SetBinding(col, DataGridColumn.VisibilityProperty, b);
            }
        }
    }
}
